name: Extract ZIP in Repository

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip file
        run: |
          unzip project.zip -d extracted

      - name: Move extracted files
        run: |
          shopt -s dotglob
          mv extracted/* .
          rm -rf extracted
          rm -f project.zip

      - name: Commit extracted files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Extracted zip file" || echo "No changes to commit"
          git push
